language: clojure

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - echo "Y" | lein upgrade 2.7.0
  - lein modules do test, install

jdk:
  - oraclejdk8

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
